language: minimal
dist: bionic

services:
  - docker

env:
  matrix:
    - ARCH=armhf DISTRO=wheezy
    - ARCH=armhf DISTRO=jessie
    - ARCH=armhf DISTRO=stretch
    - ARCH=armhf DISTRO=buster
    - ARCH=amd64 DISTRO=wheezy
    - ARCH=amd64 DISTRO=jessie
    - ARCH=amd64 DISTRO=stretch
    - ARCH=amd64 DISTRO=buster
    - ARCH=i386 DISTRO=wheezy
    - ARCH=i386 DISTRO=jessie
    - ARCH=i386 DISTRO=stretch
    - ARCH=i386 DISTRO=buster
    - ARCH=armel DISTRO=wheezy
    - ARCH=armel DISTRO=jessie
    - ARCH=armel DISTRO=stretch
    - ARCH=armel DISTRO=buster
    - ARCH=arm64 DISTRO=jessie
    - ARCH=arm64 DISTRO=stretch
    - ARCH=arm64 DISTRO=buster

script:
  - make ARCH=${ARCH} DISTRO=${DISTRO}
  - make upload ARCH=${ARCH} DISTRO=${DISTRO} DOCKER_USER=${DOCKER_USER} DOCKER_EMAIL=${DOCKER_EMAIL} DOCKER_PASSWORD=${DOCKER_PASSWORD}
