sudo: required

language: c

services:
  - docker

env:
  matrix:
    - ARCH=armhf DISTRO=wheezy
    - ARCH=armhf DISTRO=jessie

script:
  - make ARCH=${ARCH} DISTRO=${DISTRO}
  - make upload DOCKER_USER=${DOCKER_USER} DOCKER_EMAIL=${DOCKER_EMAIL} DOCKER_PASSWORD=${DOCKER_PASSWORD}
